In [7]:
import pandas as pd

from data_functions import load_maddison

In [11]:
maddison_df = load_maddison()

In [12]:
maddison_df.head()

  countrycode      country                     region  year  gdppc  pop
0         AFG  Afghanistan  South and South East Asia     1    NaN  NaN
1         AFG  Afghanistan  South and South East Asia   730    NaN  NaN
2         AFG  Afghanistan  South and South East Asia  1000    NaN  NaN
3         AFG  Afghanistan  South and South East Asia  1090    NaN  NaN
4         AFG  Afghanistan  South and South East Asia  1150    NaN  NaN

In [13]:
maddison_df

,countrycode,country,region,year,gdppc,pop
0,AFG,Afghanistan,South and South East Asia,1,NaN,NaN
1,AFG,Afghanistan,South and South East Asia,730,NaN,NaN
2,AFG,Afghanistan,South and South East Asia,1000,NaN,NaN
3,AFG,Afghanistan,South and South East Asia,1090,NaN,NaN
4,AFG,Afghanistan,South and South East Asia,1150,NaN,NaN
...,...,...,...,...,...,...
131139,ZWE,Zimbabwe,Sub Saharan Africa,2018,1900.199191,14096.56
131140,ZWE,Zimbabwe,Sub Saharan Africa,2019,1753.024449,14344.59
131141,ZWE,Zimbabwe,Sub Saharan Africa,2020,1585.972804,14614.82
131142,ZWE,Zimbabwe,Sub Saharan Africa,2021,1687.253154,14900.01
131143,ZWE,Zimbabwe,Sub Saharan Africa,2022,1703.529373,15204.66

In [92]:
from data_functions import load_vdem
v_dem_df = load_vdem()

In [10]:
print("Rows:", len(v_dem_df))
print("Columns:", len(v_dem_df.columns))
print("Columns available:", v_dem_df.columns.tolist())

Rows: 27913
Columns: 5
Columns available: ['country_name', 'year', 'v2x_regime', 'v2x_polyarchy', 'v2x_liberal']

In [14]:
print("Rows:", len(maddison_df))
print("Columns:", len(maddison_df.columns))
print("Columns available:", maddison_df.columns.tolist())

Rows: 131144
Columns: 6
Columns available: ['countrycode', 'country', 'region', 'year', 'gdppc', 'pop']

In [15]:
maddison_df[maddison_df["country"] == "Germany"]

      countrycode  country          region  year         gdppc       pop
30264         DEU  Germany  Western Europe     1           NaN   3000.00
30265         DEU  Germany  Western Europe   730           NaN       NaN
30266         DEU  Germany  Western Europe  1000           NaN   3500.00
30267         DEU  Germany  Western Europe  1090           NaN       NaN
30268         DEU  Germany  Western Europe  1150           NaN       NaN
...           ...      ...             ...   ...           ...       ...
31035         DEU  Germany  Western Europe  2018  46377.390853  82923.13
31036         DEU  Germany  Western Europe  2019  46761.946056  83110.16
31037         DEU  Germany  Western Europe  2020  44996.429621  83178.18
31038         DEU  Germany  Western Europe  2021  46159.051881  83213.19
31039         DEU  Germany  Western Europe  2022  46647.791917  83811.31

[776 rows x 6 columns]

In [16]:
v_dem_df[v_dem_df["country_name"] == "Germany"][["country_name", "year", "v2x_regime"]]

      country_name  year  v2x_regime
11712      Germany  1789         NaN
11713      Germany  1790         NaN
11714      Germany  1791         NaN
11715      Germany  1792         NaN
11716      Germany  1793         NaN
...            ...   ...         ...
11939      Germany  2020         3.0
11940      Germany  2021         3.0
11941      Germany  2022         3.0
11942      Germany  2023         3.0
11943      Germany  2024         3.0

[232 rows x 3 columns]

In [17]:
# Delete all observations before the 1900s and all observations after 2022 for the v-dem data

v_dem_df = v_dem_df[(v_dem_df["year"] >= 1900) & (v_dem_df["year"] <= 2022)]

In [74]:
v_dem_df[v_dem_df["country"] == "Germany"]

       country  year  v2x_regime  v2x_polyarchy  v2x_liberal
11823  Germany  1900         0.0          0.239        0.661
11824  Germany  1901         0.0          0.238        0.662
11825  Germany  1902         0.0          0.238        0.658
11826  Germany  1903         0.0          0.247        0.660
11827  Germany  1904         0.0          0.254        0.660
...        ...   ...         ...            ...          ...
11937  Germany  2018         3.0          0.880        0.960
11938  Germany  2019         3.0          0.882        0.960
11939  Germany  2020         3.0          0.872        0.959
11940  Germany  2021         3.0          0.864        0.959
11941  Germany  2022         3.0          0.854        0.959

[119 rows x 5 columns]

In [19]:
# Delete all observations before the 1900s and all observations after 2022 for the maddison data
maddison_df = maddison_df[(maddison_df["year"] >= 1900) & (maddison_df["year"] <= 2022)]

In [77]:
maddison_df[(maddison_df["country"] == "Germany")]

      countrycode  country          region  year         gdppc       pop
30917         DEU  Germany  Western Europe  1900   4758.000000  54388.00
30918         DEU  Germany  Western Europe  1901   4576.000000  55214.00
30919         DEU  Germany  Western Europe  1902   4611.000000  56104.00
30920         DEU  Germany  Western Europe  1903   4795.000000  56963.00
30921         DEU  Germany  Western Europe  1904   4914.000000  57806.00
...           ...      ...             ...   ...           ...       ...
31035         DEU  Germany  Western Europe  2018  46377.390853  82923.13
31036         DEU  Germany  Western Europe  2019  46761.946056  83110.16
31037         DEU  Germany  Western Europe  2020  44996.429621  83178.18
31038         DEU  Germany  Western Europe  2021  46159.051881  83213.19
31039         DEU  Germany  Western Europe  2022  46647.791917  83811.31

[123 rows x 6 columns]

In [44]:
print(v_dem_df["country_name"].unique())

print(maddison_df["country"].unique())

['Mexico' 'Suriname' 'Sweden' 'Switzerland' 'Ghana' 'South Africa' 'Japan'
 'Burma/Myanmar' 'Russia' 'Albania' 'Egypt' 'Yemen' 'Colombia' 'Poland'
 'Brazil' 'United States of America' 'Portugal' 'El Salvador'
 'South Yemen' 'Bangladesh' 'Bolivia' 'Haiti' 'Honduras' 'Mali' 'Pakistan'
 'Peru' 'Senegal' 'South Sudan' 'Sudan' 'Vietnam' 'Republic of Vietnam'
 'Afghanistan' 'Argentina' 'Ethiopia' 'India' 'Kenya' 'North Korea'
 'South Korea' 'Kosovo' 'Lebanon' 'Nigeria' 'Philippines' 'Tanzania'
 'Taiwan' 'Thailand' 'Uganda' 'Venezuela' 'Benin' 'Bhutan' 'Burkina Faso'
 'Cambodia' 'Indonesia' 'Mozambique' 'Nepal' 'Nicaragua' 'Niger' 'Zambia'
 'Zimbabwe' 'Guinea' 'Ivory Coast' 'Mauritania' 'Canada' 'Australia'
 'Botswana' 'Burundi' 'Cape Verde' 'Central African Republic' 'Chile'
 'Costa Rica' 'Timor-Leste' 'Ecuador' 'France' 'Germany' 'Guatemala'
 'Iran' 'Iraq' 'Ireland' 'Italy' 'Jordan' 'Latvia' 'Lesotho' 'Liberia'
 'Malawi' 'Maldives' 'Mongolia' 'Morocco' 'Netherlands' 'Panama'
 'Papua New Guinea' 'Qatar' 'Sierra Leone' 'Spain' 'Syria' 'Tunisia'
 'Türkiye' 'Ukraine' 'United Kingdom' 'Uruguay' 'Algeria' 'Angola'
 'Armenia' 'Azerbaijan' 'Belarus' 'Cameroon' 'Chad' 'China'
 'Democratic Republic of the Congo' 'Republic of the Congo' 'Djibouti'
 'Dominican Republic' 'Eritrea' 'Gabon' 'The Gambia' 'Georgia'
 'Guinea-Bissau' 'Jamaica' 'Kazakhstan' 'Kyrgyzstan' 'Laos' 'Libya'
 'Madagascar' 'Moldova' 'Namibia' 'Palestine/West Bank' 'Rwanda' 'Somalia'
 'Sri Lanka' 'Eswatini' 'Tajikistan' 'Togo' 'Trinidad and Tobago'
 'Turkmenistan' 'German Democratic Republic' 'Palestine/Gaza' 'Somaliland'
 'Uzbekistan' 'Austria' 'Bahrain' 'Barbados' 'Belgium'
 'Bosnia and Herzegovina' 'Bulgaria' 'Comoros' 'Croatia' 'Cuba' 'Cyprus'
 'Czechia' 'Denmark' 'Equatorial Guinea' 'Estonia' 'Fiji' 'Finland'
 'Greece' 'Guyana' 'Hong Kong' 'Iceland' 'Israel' 'Kuwait' 'Lithuania'
 'Luxembourg' 'North Macedonia' 'Malaysia' 'Malta' 'Mauritius'
 'Montenegro' 'New Zealand' 'Norway' 'Oman' 'Paraguay' 'Romania'
 'Sao Tome and Principe' 'Saudi Arabia' 'Serbia' 'Seychelles' 'Singapore'
 'Slovakia' 'Slovenia' 'Solomon Islands' 'Vanuatu' 'United Arab Emirates'
 'Palestine/British Mandate' 'Hungary' 'Zanzibar']
['Afghanistan' 'Angola' 'Albania' 'United Arab Emirates' 'Argentina'
 'Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Burundi' 'Belgium' 'Benin'
 'Burkina Faso' 'Bangladesh' 'Bulgaria' 'Bahrain' 'Bosnia and Herzegovina'
 'Belarus' 'Bolivia (Plurinational State of)' 'Brazil' 'Barbados'
 'Botswana' 'Central African Republic' 'Canada' 'Switzerland' 'Chile'
 'China' "Côte d'Ivoire" 'Cameroon' 'D.R. of the Congo' 'Congo' 'Colombia'
 'Comoros' 'Cabo Verde' 'Costa Rica' 'Czechoslovakia' 'Cuba' 'Cyprus'
 'Czech Republic' 'Germany' 'Djibouti' 'Dominica' 'Denmark'
 'Dominican Republic' 'Algeria' 'Ecuador' 'Egypt' 'Spain' 'Estonia'
 'Ethiopia' 'Finland' 'France' 'Gabon' 'United Kingdom' 'Georgia' 'Ghana'
 'Guinea' 'Gambia' 'Guinea-Bissau' 'Equatorial Guinea' 'Greece'
 'Guatemala' 'China, Hong Kong SAR' 'Honduras' 'Croatia' 'Haiti' 'Hungary'
 'Indonesia' 'India' 'Ireland' 'Iran (Islamic Republic of)' 'Iraq'
 'Iceland' 'Israel' 'Italy' 'Jamaica' 'Jordan' 'Japan' 'Kazakhstan'
 'Kenya' 'Kyrgyzstan' 'Cambodia' 'Republic of Korea' 'Kuwait'
 "Lao People's DR" 'Lebanon' 'Liberia' 'Libya' 'Saint Lucia' 'Sri Lanka'
 'Lesotho' 'Lithuania' 'Luxembourg' 'Latvia' 'Morocco'
 'Republic of Moldova' 'Madagascar' 'Mexico' 'TFYR of Macedonia' 'Mali'
 'Malta' 'Myanmar' 'Montenegro' 'Mongolia' 'Mozambique' 'Mauritania'
 'Mauritius' 'Malawi' 'Malaysia' 'Namibia' 'Niger' 'Nigeria' 'Nicaragua'
 'Netherlands' 'Norway' 'Nepal' 'New Zealand' 'Oman' 'Pakistan' 'Panama'
 'Peru' 'Philippines' 'Poland' 'Puerto Rico' 'D.P.R. of Korea' 'Portugal'
 'Paraguay' 'State of Palestine' 'Qatar' 'Romania' 'Russian Federation'
 'Rwanda' 'Saudi Arabia' 'Sudan (Former)' 'Senegal' 'Singapore'
 'Sierra Leone' 'El Salvador' 'Serbia' 'Sao Tome and Principe'
 'Former USSR' 'Slovakia' 'Slovenia' 'Sweden' 'Swaziland' 'Seychelles'
 'Syrian Arab Republic' 'Chad' 'Togo' 'Thailand' 'Tajikistan'
 'Turkmenistan' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'Taiwan, Province of China' 'U.R. of Tanzania: Mainland' 'Uganda'
 'Ukraine' 'Uruguay' 'United States' 'Uzbekistan'
 'Venezuela (Bolivarian Republic of)' 'Viet Nam' 'Yemen'
 'Former Yugoslavia' 'South Africa' 'Zambia' 'Zimbabwe']

In [32]:
from thefuzz import process

# Example: find closest matches for Maddison names in V-Dem
unique_v_dem = v_dem_df["country_name"].unique()
unique_maddison = maddison_df["country"].unique()

matches = {m: process.extractOne(m, unique_v_dem)[0] for m in unique_maddison}

In [33]:
print(matches)

{'Afghanistan': 'Afghanistan', 'Angola': 'Angola', 'Albania': 'Albania', 'United Arab Emirates': 'United Arab Emirates', 'Argentina': 'Argentina', 'Armenia': 'Armenia', 'Australia': 'Australia', 'Austria': 'Austria', 'Azerbaijan': 'Azerbaijan', 'Burundi': 'Burundi', 'Belgium': 'Belgium', 'Benin': 'Benin', 'Burkina Faso': 'Burkina Faso', 'Bangladesh': 'Bangladesh', 'Bulgaria': 'Bulgaria', 'Bahrain': 'Bahrain', 'Bosnia and Herzegovina': 'Bosnia and Herzegovina', 'Belarus': 'Belarus', 'Bolivia (Plurinational State of)': 'Bolivia', 'Brazil': 'Brazil', 'Barbados': 'Barbados', 'Botswana': 'Botswana', 'Central African Republic': 'Central African Republic', 'Canada': 'Canada', 'Switzerland': 'Switzerland', 'Chile': 'Chile', 'China': 'China', "Côte d'Ivoire": 'Israel', 'Cameroon': 'Cameroon', 'D.R. of the Congo': 'Democratic Republic of the Congo', 'Congo': 'Democratic Republic of the Congo', 'Colombia': 'Colombia', 'Comoros': 'Comoros', 'Cabo Verde': 'Cape Verde', 'Costa Rica': 'Costa Rica', 'Czechoslovakia': 'Slovakia', 'Cuba': 'Cuba', 'Cyprus': 'Cyprus', 'Czech Republic': 'Central African Republic', 'Germany': 'Germany', 'Djibouti': 'Djibouti', 'Dominica': 'Dominican Republic', 'Denmark': 'Denmark', 'Dominican Republic': 'Dominican Republic', 'Algeria': 'Algeria', 'Ecuador': 'Ecuador', 'Egypt': 'Egypt', 'Spain': 'Spain', 'Estonia': 'Estonia', 'Ethiopia': 'Ethiopia', 'Finland': 'Finland', 'France': 'France', 'Gabon': 'Gabon', 'United Kingdom': 'United Kingdom', 'Georgia': 'Georgia', 'Ghana': 'Ghana', 'Guinea': 'Guinea', 'Gambia': 'The Gambia', 'Guinea-Bissau': 'Guinea-Bissau', 'Equatorial Guinea': 'Equatorial Guinea', 'Greece': 'Greece', 'Guatemala': 'Guatemala', 'China, Hong Kong SAR': 'China', 'Honduras': 'Honduras', 'Croatia': 'Croatia', 'Haiti': 'Haiti', 'Hungary': 'Hungary', 'Indonesia': 'Indonesia', 'India': 'India', 'Ireland': 'Ireland', 'Iran (Islamic Republic of)': 'Iran', 'Iraq': 'Iraq', 'Iceland': 'Iceland', 'Israel': 'Israel', 'Italy': 'Italy', 'Jamaica': 'Jamaica', 'Jordan': 'Jordan', 'Japan': 'Japan', 'Kazakhstan': 'Kazakhstan', 'Kenya': 'Kenya', 'Kyrgyzstan': 'Kyrgyzstan', 'Cambodia': 'Cambodia', 'Republic of Korea': 'North Korea', 'Kuwait': 'Kuwait', "Lao People's DR": 'Laos', 'Lebanon': 'Lebanon', 'Liberia': 'Liberia', 'Libya': 'Libya', 'Saint Lucia': 'Spain', 'Sri Lanka': 'Sri Lanka', 'Lesotho': 'Lesotho', 'Lithuania': 'Lithuania', 'Luxembourg': 'Luxembourg', 'Latvia': 'Latvia', 'Morocco': 'Morocco', 'Republic of Moldova': 'Moldova', 'Madagascar': 'Madagascar', 'Mexico': 'Mexico', 'TFYR of Macedonia': 'Democratic Republic of the Congo', 'Mali': 'Mali', 'Malta': 'Malta', 'Myanmar': 'Burma/Myanmar', 'Montenegro': 'Montenegro', 'Mongolia': 'Mongolia', 'Mozambique': 'Mozambique', 'Mauritania': 'Mauritania', 'Mauritius': 'Mauritius', 'Malawi': 'Malawi', 'Malaysia': 'Malaysia', 'Namibia': 'Namibia', 'Niger': 'Niger', 'Nigeria': 'Nigeria', 'Nicaragua': 'Nicaragua', 'Netherlands': 'Netherlands', 'Norway': 'Norway', 'Nepal': 'Nepal', 'New Zealand': 'New Zealand', 'Oman': 'Oman', 'Pakistan': 'Pakistan', 'Panama': 'Panama', 'Peru': 'Peru', 'Philippines': 'Philippines', 'Poland': 'Poland', 'Puerto Rico': 'Peru', 'D.P.R. of Korea': 'United States of America', 'Portugal': 'Portugal', 'Paraguay': 'Paraguay', 'State of Palestine': 'Democratic Republic of the Congo', 'Qatar': 'Qatar', 'Romania': 'Romania', 'Russian Federation': 'Russia', 'Rwanda': 'Rwanda', 'Saudi Arabia': 'Saudi Arabia', 'Sudan (Former)': 'Sudan', 'Senegal': 'Senegal', 'Singapore': 'Singapore', 'Sierra Leone': 'Sierra Leone', 'El Salvador': 'El Salvador', 'Serbia': 'Serbia', 'Sao Tome and Principe': 'Sao Tome and Principe', 'Former USSR': 'Peru', 'Slovakia': 'Slovakia', 'Slovenia': 'Slovenia', 'Sweden': 'Sweden', 'Swaziland': 'Somaliland', 'Seychelles': 'Seychelles', 'Syrian Arab Republic': 'Syria', 'Chad': 'Chad', 'Togo': 'Togo', 'Thailand': 'Thailand', 'Tajikistan': 'Tajikistan', 'Turkmenistan': 'Turkmenistan', 'Trinidad and Tobago': 'Trinidad and Tobago', 'Tunisia': 'Tunisia', 'Turkey': 'Turkmenistan', 'Taiwan, Province of China': 'Taiwan', 'U.R. of Tanzania: Mainland': 'Tanzania', 'Uganda': 'Uganda', 'Ukraine': 'Ukraine', 'Uruguay': 'Uruguay', 'United States': 'United States of America', 'Uzbekistan': 'Uzbekistan', 'Venezuela (Bolivarian Republic of)': 'Venezuela', 'Viet Nam': 'Vietnam', 'Yemen': 'Yemen', 'Former Yugoslavia': 'Latvia', 'South Africa': 'South Africa', 'Zambia': 'Zambia', 'Zimbabwe': 'Zimbabwe'}

In [40]:
# Step 1: Creates a dictionary with all the unique country names in both datasets

matches = {}
for m in unique_maddison:
    best_match, score = process.extractOne(m, unique_v_dem)
    matches[m] = {"best_match": best_match, "score": score}

# Step 2: Converts the dictionary to a DataFrame
matches_df = pd.DataFrame([
    {"maddison_name": k, "vdem_match": v["best_match"], "score": v["score"]}
    for k, v in matches.items()
])

In [43]:
matches_df

            maddison_name            vdem_match  score
0             Afghanistan           Afghanistan    100
1                  Angola                Angola    100
2                 Albania               Albania    100
3    United Arab Emirates  United Arab Emirates    100
4               Argentina             Argentina    100
..                    ...                   ...    ...
164                 Yemen                 Yemen    100
165     Former Yugoslavia                Latvia     82
166          South Africa          South Africa    100
167                Zambia                Zambia    100
168              Zimbabwe              Zimbabwe    100

[169 rows x 3 columns]

In [ ]:

#  Former USSR,Somaliland, Somalia, Turkey, Dominica are missing from either datasets
#  State of Palestine >> Palestine/west bank - Palestine/Gaza

In [45]:
# Matches all the names in both datasest to be able to merge both dataframes
v_dem_df["country_name"].replace({
    "Bolivia (Plurinational State of)": "Bolivia",
    "D.R. of the Congo": "Democratic Republic of the Congo",
    "Iran": "Iran (Islamic Republic of)",
    "Burma/Myanmar" : "Myanmar",
    "Ivory Coast":"Côte d'Ivoire",
    "Czechia":"Czech Republic"
}, inplace=True)

maddison_df["country"].replace({
    "The Gambia": "Gambia",
    "United States": "United States of America",
    "Lao People's DR": "Laos",
    "Republic of Moldova" : "Moldova",
    "Russian Federation" : "Russia",
    "Sudan (Former)" : "Sudan",
    "Syrian Arab Republic" :"Syria",
    "Taiwan, Province of China" : "Taiwan",
    "Cabo Verde":"Cape Verde",
    "Swaziland":"Eswatini",
    "Congo":"Republic of the Congo",
    "China, Hong Kong SAR" : "Hong Kong",
    "D.P.R. of Korea":"North Korea",
    "Republic of Korea" : "South Korea",
    "U.R. of Tanzania: Mainland":"Tanzania",
    "Venezuela (Bolivarian Republic of)":" Venezuela",
    "Viet Nam":"Vietnam"
     #Zanzibar is excluded from the v_dem data set and is added as a seperate country


}, inplace=True)

/var/folders/4f/qxlwg6z95tgd3by8tpxwc6kh0000gn/T/ipykernel_66465/810536676.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  v_dem_df["country_name"].replace({
/var/folders/4f/qxlwg6z95tgd3by8tpxwc6kh0000gn/T/ipykernel_66465/810536676.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  maddison_df["country"].replace({
/var/folders/4f/qxlwg6z95tgd3by8tpxwc6kh0000gn/T/ipykernel_66465/810536676.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  maddison_df["country"].replace({

In [50]:
v_dem_df[v_dem_df["country_name"] == "Bolivia"]

     country_name  year  v2x_regime  v2x_polyarchy  v2x_liberal
3819      Bolivia  1900         1.0          0.172        0.235
3820      Bolivia  1901         1.0          0.172        0.239
3821      Bolivia  1902         1.0          0.172        0.239
3822      Bolivia  1903         1.0          0.172        0.239
3823      Bolivia  1904         1.0          0.174        0.239
...           ...   ...         ...            ...          ...
3937      Bolivia  2018         2.0          0.598        0.497
3938      Bolivia  2019         1.0          0.481        0.428
3939      Bolivia  2020         1.0          0.331        0.546
3940      Bolivia  2021         2.0          0.614        0.520
3941      Bolivia  2022         2.0          0.589        0.507

[123 rows x 5 columns]

In [51]:
v_dem_df.rename(columns={"country_name": "country"}, inplace=True)

In [61]:
# Merge both data sets
merged_df = pd.merge(v_dem_df, maddison_df, on=["country", "year"], how="inner")  # inner join keeps only matching rows
merged_df

,country,year,v2x_regime,v2x_polyarchy,v2x_liberal,countrycode,region,gdppc,pop
0,Mexico,1900,0.0,0.124,0.184,MEX,Latin America,1822.000000,13607.00
1,Mexico,1901,0.0,0.108,0.184,MEX,Latin America,1957.000000,13755.00
2,Mexico,1902,0.0,0.108,0.184,MEX,Latin America,1796.000000,13904.00
3,Mexico,1903,0.0,0.108,0.184,MEX,Latin America,1978.000000,14055.00
4,Mexico,1904,0.0,0.108,0.184,MEX,Latin America,1992.000000,14208.00
...,...,...,...,...,...,...,...,...,...
16731,Hungary,2018,1.0,0.483,0.723,HUN,Eastern Europe,25995.509006,9782.04
16732,Hungary,2019,1.0,0.471,0.716,HUN,Eastern Europe,27272.312085,9777.62
16733,Hungary,2020,1.0,0.468,0.708,HUN,Eastern Europe,26091.400330,9756.62
16734,Hungary,2021,1.0,0.452,0.703,HUN,Eastern Europe,28085.962226,9716.33
16735,Hungary,2022,1.0,0.452,0.674,HUN,Eastern Europe,29451.855787,9689.89

In [79]:
merged_df[["country", "year", "v2x_regime", "region", "gdppc", "pop" ]][merged_df['country'] == "Germany"]

      country  year  v2x_regime          region         gdppc       pop
7329  Germany  1900         0.0  Western Europe   4758.000000  54388.00
7330  Germany  1901         0.0  Western Europe   4576.000000  55214.00
7331  Germany  1902         0.0  Western Europe   4611.000000  56104.00
7332  Germany  1903         0.0  Western Europe   4795.000000  56963.00
7333  Germany  1904         0.0  Western Europe   4914.000000  57806.00
...       ...   ...         ...             ...           ...       ...
7443  Germany  2018         3.0  Western Europe  46377.390853  82923.13
7444  Germany  2019         3.0  Western Europe  46761.946056  83110.16
7445  Germany  2020         3.0  Western Europe  44996.429621  83178.18
7446  Germany  2021         3.0  Western Europe  46159.051881  83213.19
7447  Germany  2022         3.0  Western Europe  46647.791917  83811.31

[119 rows x 6 columns]

In [93]:
print("Rows:", len(merged_df))
print("Columns:", len(merged_df.columns))
print("Columns available:", merged_df.columns.tolist())
print((len(maddison_df["country"].unique())))

Rows: 16736
Columns: 9
Columns available: ['country', 'year', 'v2x_regime', 'v2x_polyarchy', 'v2x_liberal', 'countrycode', 'region', 'gdppc', 'pop']
169

In [1]:
from data_functions import load_popgrowth_df

In [2]:
pop_growth_df = load_popgrowth_df()

In [3]:
pop_growth_df

,country,year,Population growth rate - Sex: all - Age: all - Variant: estimates
0,Afghanistan,1950,1.275
1,Afghanistan,1951,1.360
2,Afghanistan,1952,1.374
3,Afghanistan,1953,1.335
4,Afghanistan,1954,1.394
...,...,...,...
18716,Zimbabwe,2018,1.518
18717,Zimbabwe,2019,1.609
18718,Zimbabwe,2020,1.709
18719,Zimbabwe,2021,1.743
18720,Zimbabwe,2022,1.670

In [1]:
from data_functions import load_trade_share

In [2]:
trade_share_df = load_trade_share()

In [6]:
trade_share_df

INDICATOR,country,year,"Exports of goods, Free on board (FOB), US dollar","Imports of goods, Cost insurance freight (CIF), US dollar",export_share
0,Advanced Economies,1948,35391.100000,38855.950000,0.476667
1,Advanced Economies,1949,36919.000000,39108.230000,0.485602
2,Advanced Economies,1950,36361.700000,40278.730000,0.474445
3,Advanced Economies,1951,52632.900000,54785.140000,0.489982
4,Advanced Economies,1952,50413.200000,53551.110000,0.484909
...,...,...,...,...,...
12984,Zimbabwe,2018,3531.595547,7542.572349,0.318904
12985,Zimbabwe,2019,3642.864845,6268.184894,0.367556
12986,Zimbabwe,2020,4394.811685,7021.975998,0.384943
12987,Zimbabwe,2021,6036.187305,9112.979255,0.398450
12988,Zimbabwe,2022,6585.479341,9758.189551,0.402938

In [1]:
from data_functions import load_infant_mortality

In [2]:
infant_mortality_df = load_infant_mortality()

In [4]:
infant_mortality_df

,Country Name,Series Name,year,Value
0,Afghanistan,"Mortality rate, infant (per 1,000 live births)",1960,251.2
1,Albania,"Mortality rate, infant (per 1,000 live births)",1960,..
2,Algeria,"Mortality rate, infant (per 1,000 live births)",1960,161.8
3,American Samoa,"Mortality rate, infant (per 1,000 live births)",1960,..
4,Andorra,"Mortality rate, infant (per 1,000 live births)",1960,..
...,...,...,...,...
15241,NaN,NaN,2022,NaN
15242,NaN,NaN,2022,NaN
15243,NaN,NaN,2022,NaN
15244,NaN,Data from database: World Development Indicators,2022,NaN
15245,NaN,Last Updated: 10/07/2025,2022,NaN

In [5]:
infant_mortality_df[infant_mortality_df["Country Name"] == "Germany" ]

      Country Name                                     Series Name  year Value
73         Germany  Mortality rate, infant (per 1,000 live births)  1960    ..
315        Germany  Mortality rate, infant (per 1,000 live births)  1961    ..
557        Germany  Mortality rate, infant (per 1,000 live births)  1962    ..
799        Germany  Mortality rate, infant (per 1,000 live births)  1963    ..
1041       Germany  Mortality rate, infant (per 1,000 live births)  1964    ..
...            ...                                             ...   ...   ...
14109      Germany  Mortality rate, infant (per 1,000 live births)  2018   3.2
14351      Germany  Mortality rate, infant (per 1,000 live births)  2019   3.1
14593      Germany  Mortality rate, infant (per 1,000 live births)  2020   3.1
14835      Germany  Mortality rate, infant (per 1,000 live births)  2021   3.1
15077      Germany  Mortality rate, infant (per 1,000 live births)  2022   3.1

[63 rows x 4 columns]

In [5]:
df = pd.read_excel('/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/TFP_Data.xlsx')

In [8]:
df.columns

Index(['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '1960 [YR1960]', '1961 [YR1961]', '1962 [YR1962]', '1963 [YR1963]',
       '1964 [YR1964]', '1965 [YR1965]', '1966 [YR1966]', '1967 [YR1967]',
       '1968 [YR1968]', '1969 [YR1969]', '1970 [YR1970]', '1971 [YR1971]',
       '1972 [YR1972]', '1973 [YR1973]', '1974 [YR1974]', '1975 [YR1975]',
       '1976 [YR1976]', '1977 [YR1977]', '1978 [YR1978]', '1979 [YR1979]',
       '1980 [YR1980]', '1981 [YR1981]', '1982 [YR1982]', '1983 [YR1983]',
       '1984 [YR1984]', '1985 [YR1985]', '1986 [YR1986]', '1987 [YR1987]',
       '1988 [YR1988]', '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]',
       '1992 [YR1992]', '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]',
       '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]',
       '2024 [YR2024]'],
      dtype='object')

In [2]:
import pandas as pd

In [8]:
from data_functions import load_TFP

In [9]:
tfp_df = load_TFP()

In [10]:
tfp_df

        country  year    rtfpna
0         Aruba  1950       NaN
1         Aruba  1951       NaN
2         Aruba  1952       NaN
3         Aruba  1953       NaN
4         Aruba  1954       NaN
...         ...   ...       ...
12805  Zimbabwe  2015  0.999666
12806  Zimbabwe  2016  0.980511
12807  Zimbabwe  2017  1.000000
12808  Zimbabwe  2018  1.018163
12809  Zimbabwe  2019  0.917617

[12810 rows x 3 columns]

In [13]:
tfp_df[tfp_df["country"] == "Egypt"]

     country  year    rtfpna
3710   Egypt  1950       NaN
3711   Egypt  1951       NaN
3712   Egypt  1952       NaN
3713   Egypt  1953       NaN
3714   Egypt  1954  1.113912
...      ...   ...       ...
3775   Egypt  2015  0.977401
3776   Egypt  2016  0.986225
3777   Egypt  2017  1.000000
3778   Egypt  2018  1.006566
3779   Egypt  2019  1.013955

[70 rows x 3 columns]

In [14]:
v_dem = pd.read_csv('/Users/ghadaelhusseini/Downloads/V-Dem-CY-FullOthers-v15_csv/V-Dem-CY-Full+Others-v15.csv')

/var/folders/4f/qxlwg6z95tgd3by8tpxwc6kh0000gn/T/ipykernel_70299/2160555786.py:1: DtypeWarning: Columns (364,365,366,399,804,836,837,924,1240,1257,1486,3094,3168,3169,3341,3342,3344,3345,3347,3350,3352) have mixed types. Specify dtype option on import or set low_memory=False.
  v_dem = pd.read_csv('/Users/ghadaelhusseini/Downloads/V-Dem-CY-FullOthers-v15_csv/V-Dem-CY-Full+Others-v15.csv')

In [1]:
from data_functions import load_vdem_corr

In [2]:
vdem_corr_df = load_vdem_corr()

/Users/ghadaelhusseini/PyCharmMiscProject/data_functions.py:145: DtypeWarning: Columns (364,365,366,399,804,836,837,924,1240,1257,1486,3094,3168,3169,3341,3342,3344,3345,3347,3350,3352) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/V-Dem-CY-Full+Others-v15.csv')

KeyError: "['country'] not in index"

In [6]:
df = pd.read_csv('/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/V-Dem-CY-Full+Others-v15.csv')

/var/folders/4f/qxlwg6z95tgd3by8tpxwc6kh0000gn/T/ipykernel_71210/2172077021.py:1: DtypeWarning: Columns (364,365,366,399,804,836,837,924,1240,1257,1486,3094,3168,3169,3341,3342,3344,3345,3347,3350,3352) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/V-Dem-CY-Full+Others-v15.csv')

In [2]:
import pandas as pd

In [7]:
df.columns

Index(['country_name', 'country_text_id', 'country_id', 'year',
       'historical_date', 'project', 'historical', 'histname', 'codingstart',
       'codingend',
       ...
       'e_mipopula', 'e_miurbani', 'e_pefeliex', 'e_wb_pop', 'e_pechmor',
       'e_miinteco', 'e_civil_war', 'e_miinterc', 'e_pt_coup',
       'e_pt_coup_attempts'],
      dtype='object', length=4607)

In [1]:
from data_functions import load_vdem_corr

In [2]:
vdem_corr = load_vdem_corr()

/Users/ghadaelhusseini/PyCharmMiscProject/data_functions.py:145: DtypeWarning: Columns (364,365,366,399,804,836,837,924,1240,1257,1486,3094,3168,3169,3341,3342,3344,3345,3347,3350,3352) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/V-Dem-CY-Full+Others-v15.csv')

In [3]:
vdem_corr

        country  year  v2x_corr  v2x_execorr  v2x_pubcorr
161      Mexico  1950     0.819        0.828        0.760
162      Mexico  1951     0.819        0.828        0.760
163      Mexico  1952     0.819        0.828        0.760
164      Mexico  1953     0.819        0.828        0.760
165      Mexico  1954     0.819        0.828        0.760
...         ...   ...       ...          ...          ...
26507  Zanzibar  2018     0.659        0.710        0.731
26508  Zanzibar  2019     0.695        0.708        0.731
26509  Zanzibar  2020     0.693        0.708        0.723
26510  Zanzibar  2021     0.707        0.722        0.763
26511  Zanzibar  2022     0.657        0.722        0.763

[12109 rows x 5 columns]

In [2]:
import pandas as pd

In [10]:
from data_functions import load_eth_frac

In [12]:
eth_frac = load_eth_frac()

In [13]:
eth_frac

           country  year  fe_etfra
4      Afghanistan  1950  0.750797
5      Afghanistan  1951  0.750797
6      Afghanistan  1952  0.750797
7      Afghanistan  1953  0.750797
8      Afghanistan  1954  0.750797
...            ...   ...       ...
10117     Pakistan  1966  0.532100
10118     Pakistan  1967  0.532100
10119     Pakistan  1968  0.532100
10120     Pakistan  1969  0.532100
10121     Pakistan  1970  0.532100

[9547 rows x 3 columns]

In [14]:
df = pd.read_excel('/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/mpd2023_web.xlsx')

In [15]:
df

,countrycode,country,region,year,gdppc,pop
0,AFG,Afghanistan,South and South East Asia,1,NaN,NaN
1,AFG,Afghanistan,South and South East Asia,730,NaN,NaN
2,AFG,Afghanistan,South and South East Asia,1000,NaN,NaN
3,AFG,Afghanistan,South and South East Asia,1090,NaN,NaN
4,AFG,Afghanistan,South and South East Asia,1150,NaN,NaN
...,...,...,...,...,...,...
131139,ZWE,Zimbabwe,Sub Saharan Africa,2018,1900.199191,14096.56
131140,ZWE,Zimbabwe,Sub Saharan Africa,2019,1753.024449,14344.59
131141,ZWE,Zimbabwe,Sub Saharan Africa,2020,1585.972804,14614.82
131142,ZWE,Zimbabwe,Sub Saharan Africa,2021,1687.253154,14900.01
131143,ZWE,Zimbabwe,Sub Saharan Africa,2022,1703.529373,15204.66

In [17]:
df = df.sort_values(["country", "year"])
df["gdp_pc_lag1"] = df.groupby("country")["gdppc"].shift(1)

In [18]:
df

,countrycode,country,region,year,gdppc,pop,gdp_pc_lag1
0,AFG,Afghanistan,South and South East Asia,1,NaN,NaN,NaN
1,AFG,Afghanistan,South and South East Asia,730,NaN,NaN,NaN
2,AFG,Afghanistan,South and South East Asia,1000,NaN,NaN,NaN
3,AFG,Afghanistan,South and South East Asia,1090,NaN,NaN,NaN
4,AFG,Afghanistan,South and South East Asia,1150,NaN,NaN,NaN
...,...,...,...,...,...,...,...
131139,ZWE,Zimbabwe,Sub Saharan Africa,2018,1900.199191,14096.56,1843.946230
131140,ZWE,Zimbabwe,Sub Saharan Africa,2019,1753.024449,14344.59,1900.199191
131141,ZWE,Zimbabwe,Sub Saharan Africa,2020,1585.972804,14614.82,1753.024449
131142,ZWE,Zimbabwe,Sub Saharan Africa,2021,1687.253154,14900.01,1585.972804
131143,ZWE,Zimbabwe,Sub Saharan Africa,2022,1703.529373,15204.66,1687.253154

In [1]:
from data_functions import load_lag_gdppc

In [4]:
lag_gdppc = load_lag_gdppc()

In [5]:
lag_gdppc

            country  year                     region  gdp_pc_lag1
703     Afghanistan  1950  South and South East Asia          NaN
704     Afghanistan  1951  South and South East Asia  1156.000000
705     Afghanistan  1952  South and South East Asia  1170.000000
706     Afghanistan  1953  South and South East Asia  1189.000000
707     Afghanistan  1954  South and South East Asia  1240.000000
...             ...   ...                        ...          ...
131139     Zimbabwe  2018         Sub Saharan Africa  1843.946230
131140     Zimbabwe  2019         Sub Saharan Africa  1900.199191
131141     Zimbabwe  2020         Sub Saharan Africa  1753.024449
131142     Zimbabwe  2021         Sub Saharan Africa  1585.972804
131143     Zimbabwe  2022         Sub Saharan Africa  1687.253154

[12337 rows x 4 columns]

In [1]:
import pandas as pd

In [13]:
df = pd.read_csv("/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/Infant_mortality.csv")

In [15]:
df.columns

Index(['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '1960 [YR1960]', '1961 [YR1961]', '1962 [YR1962]', '1963 [YR1963]',
       '1964 [YR1964]', '1965 [YR1965]', '1966 [YR1966]', '1967 [YR1967]',
       '1968 [YR1968]', '1969 [YR1969]', '1970 [YR1970]', '1971 [YR1971]',
       '1972 [YR1972]', '1973 [YR1973]', '1974 [YR1974]', '1975 [YR1975]',
       '1976 [YR1976]', '1977 [YR1977]', '1978 [YR1978]', '1979 [YR1979]',
       '1980 [YR1980]', '1981 [YR1981]', '1982 [YR1982]', '1983 [YR1983]',
       '1984 [YR1984]', '1985 [YR1985]', '1986 [YR1986]', '1987 [YR1987]',
       '1988 [YR1988]', '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]',
       '1992 [YR1992]', '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]',
       '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]',
       '2024 [YR2024]'],
      dtype='object')

In [20]:
infant_mortality_df = pd.read_csv("/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/Infant_mortality.csv")

In [21]:
year_cols = [f"{y} [YR{y}]" for y in range(1960, 2023)]
infant_mortality_df = infant_mortality_df[['Country Name', 'Series Name'] + year_cols]

infant_mortality_df_long = infant_mortality_df.melt(
    id_vars=['Country Name', 'Series Name'],
    var_name='year',
    value_name='Value'
)

# Clean up year column
infant_mortality_df_long['year'] = infant_mortality_df_long['year'].str.extract(r'(\d{4})').astype(int)

In [28]:
infant_mortality_df_long[infant_mortality_df_long['Country Name'] == "Canada"]

      Country Name                                     Series Name  year Value
35          Canada  Mortality rate, infant (per 1,000 live births)  1960  27.8
277         Canada  Mortality rate, infant (per 1,000 live births)  1961  26.9
519         Canada  Mortality rate, infant (per 1,000 live births)  1962    26
761         Canada  Mortality rate, infant (per 1,000 live births)  1963  25.1
1003        Canada  Mortality rate, infant (per 1,000 live births)  1964  24.1
...            ...                                             ...   ...   ...
14071       Canada  Mortality rate, infant (per 1,000 live births)  2018   4.5
14313       Canada  Mortality rate, infant (per 1,000 live births)  2019   4.5
14555       Canada  Mortality rate, infant (per 1,000 live births)  2020   4.5
14797       Canada  Mortality rate, infant (per 1,000 live births)  2021   4.5
15039       Canada  Mortality rate, infant (per 1,000 live births)  2022   4.5

[63 rows x 4 columns]

In [1]:
import pandas as pd
df = pd.read_csv("/Users/ghadaelhusseini/Documents/Kassel University Masters /Thesis/my_Data/Infant_mortality.csv")
year_cols = [f"{y} [YR{y}]" for y in range(1960, 2023)]
df = df[['Country Name', 'Series Name'] + year_cols]

df = df.melt(
        id_vars=['Country Name', 'Series Name'],
        var_name='year',
        value_name='Value'
    )

# Clean up year column
df['year'] = df['year'].str.extract(r'(\d{4})').astype(int)

df = df.rename(columns={
        "Country Name": "country",
    })

#  Keeping only relevant columns: COUNTRY, INDICATOR, years
cols_to_keep = ["country", "year", "Value"]
df= df[cols_to_keep]

In [2]:
df

              country  year  Value
0         Afghanistan  1960  251.2
1             Albania  1960     ..
2             Algeria  1960  161.8
3      American Samoa  1960     ..
4             Andorra  1960     ..
...               ...   ...    ...
15241             NaN  2022    NaN
15242             NaN  2022    NaN
15243             NaN  2022    NaN
15244             NaN  2022    NaN
15245             NaN  2022    NaN

[15246 rows x 3 columns]